### ISSUE TITLE
Can't scroll logs/output

### ISSUE THREAD

**Issue by mymike00** [ubports/terminal-app#1]
when I run a command that prints out a long output there is no way to scroll it

**Comment by sverzegnassi** [comment]
Hi,

You can scroll the output of the console by performing a vertical swipe with two fingers. Unfortunately, gestures of terminal-app are not well documented.

Anyway, we are about to start a review of the status of the core apps, and we'll take in account the bad usability of terminal-app for sure.

Please let us know if the suggestion solved your issue. If not, please report all the necessary steps to reproduce your issue.

**Comment by mymike00** [comment]
oh, thanks, I didn't know it. issue solved
