### ISSUE TITLE
Taking the click build with this repository to the Openstore

### ISSUE THREAD

**Issue by wagafo** [ubports/terminal-app#5]
The click that the Openstore installs does not correspond to the click that is built from this repository. The one in the Openstore has a hack to never ask for login when the terminal app is started, and we don't have the source AFAIK. For the terminal app to be installed by default in the ubports images, the login should not be completely deactivated. That's why I contributed a patch to add a setting so that the user can disable being asked for login, but it is activated by default.

Now, I think this new click should be offered in the Openstore and installed by default in the images. I'm offering myself to maintain it. What is left to do:

1) Bump the version to a new number, I haven't touched the version number.
2) Modify the Cmakefile so that manifest.json is written from manifest.json.in. I just copied it so that the package could build.
3) Modify clickable.json so that it installs a dependency needed to build: libpam0g-dev

These are minor things and the click can be moved (IMHO) to the images and the Openstore.

**Comment by wagafo** [comment]
I forgot that there is another issue building the app with "clicable" in the translations. The pot file is build correctly but the individual language po files are not merged. I did it manually after building the package, but there should be a way to ask clickable to do it.

**Comment by NeoTheThird** [comment]
Building translations with clickable works with @sverzegnassi 's PR #7.

**Comment by wagafo** [comment]
Great, thanks.
